# Site config:
baseurl: ""  # Set to empty for local development
url: "http://localhost:4000"  # Local development URL
github_username: peterhpo
relative_permalinks: false
permalink: nyheter/:title/  # permalink: date
timezone: Europe/Oslo

include:
  - _pages

# Site content:
title: Biørnegildet 2025
email: gildestyret@rf.uio.no
description: |
  Biørnegildet 2025 - 17. - 22. Februar 2025!
logo: /static/img/social/og.png
festival_tema: "Mennesket i samfunnet (+/- 25 år)"
festival_datoer: "17.-22. Februar"
conf_year: 2025
## All the email addresses
conduct_email: "gildestyret@rf.uio.no"
contact_us_email: "gildestyret@rf.uio.no"
opportunity_grants_email: "gildestyret@rf.uio.no"
program_team_email: "gildestyret@rf.uio.no"
sponsors_email: "gildestyret@rf.uio.no"
visa_email: "gildestyret@rf.uio.no"

future: true

# Other configs:
collections:  # process the _data folder
  components:
    output: false
  schedule:
    output: true
    permalink: /:collection/:name/
  organizers:
    output: false
    permalink: /:collection/:name/
  presenters:
    output: true
    permalink: /:collection/
  sponsors:
    output: false
    permalink: /:collection/
  places:
    output: false
    permalink: /:collection/ 
  jobs:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap  # Optional: disable if not needed for local development
  - jemoji

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/img/social/avatar-main.png
  - scope:
      path: "_presenters"
      type: presenters
    values:
      sitemap: false
